### ISSUE TITLE
Enhancement Request: Water environment

### ISSUE THREAD

**Issue by Carlson-Lee** [OtagoPolytechnic/forth-street-studios-s1-24-team-1#52]
**Description:**
Create an environment for water aspect of the game.

**Current Behavior:**
Currently the map has no body of water, we should have a map that contain water for water pump, asset of water to put on the existing map.

**Proposed Enhancement:**
My preference is to find a body of water asset and implemented into any existing map.

**Benefits:**
Water can be added easily.

**Comment by PBWiseman** [comment]
We have decided this issue is out of scope.
