### ISSUE TITLE
Bug Report: Wire deleting bug

### ISSUE THREAD

**Issue by Carlson-Lee** [OtagoPolytechnic/forth-street-studios-s1-24-team-1#90]
**Description:**
Describe the issue you encountered concisely.
When placing a object on tile_3_0, connect the wire into the central building, then you place a windmill and try to place a wire over the bend, nothing should happened as intended. then you try and delete the windmill placed they will delete the bend wires that is for the solar panel
**Steps to Reproduce:**
1. place a object on tile_3_0
2. connected to central building through tile_3_4
3. then place a windmill on tile_1_4
4. try to connect a wire through tile_3_4
5. now delete windmill.
6. the bend wire is now deleted.

**Expected Behavior:**
only delete the windmill.
**Actual Behavior:**
Bend wire deleted.

**Screenshots/GIFs:**
If applicable, add visuals to help explain the issue.

**Additional Information:**
Any additional context or information about the bug.
![image](https://github.com/OtagoPolytechnic/forth-street-studios-s1-24-team-1/assets/83677521/c56ec0bc-4136-407a-8b94-4068391f48dd)
![image](https://github.com/OtagoPolytechnic/forth-street-studios-s1-24-team-1/assets/83677521/29b7de0a-e351-493b-a0a0-3a181ddf27bd)

![image](https://github.com/OtagoPolytechnic/forth-street-studios-s1-24-team-1/assets/83677521/f05d8084-1c76-4b93-ab6e-680399cc9276)

**Comment by PBWiseman** [comment]
Not reproducible on my machine. Will continue to attempt to isolate this bug
